---
- name: define distribution value for mysql upstream repository
  set_fact:
    mysql_upstream_dist: "{% if ansible_distribution == 'Fedora' %}fc{% else %}el{% endif %}{{ ansible_distribution_major_version }}"

- name: ensure mysql upstream repository is installed
  package:
    name: "http://dev.mysql.com/get/mysql80-community-release-{{ mysql_upstream_dist }}-1.noarch.rpm"

- name: disable default mysql 8.0 upstream repository
  yum_repository:
    name: mysql80-community
    description: MySQL 8.0 Community Server - Source
    baseurl: "http://repo.mysql.com/yum/mysql-8.0-community/el/7/SRPMS"
    enabled: no
  when: mysql_upstream_version != '8.0'

- name: enable relevant mysql upstream repository for specified version
  yum_repository:
    name: "mysql{{ mysql_upstream_version | replace('.', '') }}-community"
    description: "MySQL {{ mysql_upstream_version }} Community Server - Source"
    baseurl: "http://repo.mysql.com/yum/mysql-{{ mysql_upstream_version }}-community/el/7/SRPMS"
    enabled: yes
  when: mysql_upstream_version != '8.0'
